const chatList = [
	"Hello! 👋 How can I help you today?",
	"Nice to meet you! 😊 What brings you here?",
	"Is there anything specific you'd like assistance with? 🤔",
	"Hey there! 🌟 Feel free to ask me anything.",
	"Greetings! 🌈 I'm here to assist you.",
	"How's your day going? 🌞 I'm here for any questions you may have.",
	"Welcome! 🎉 Let me know what you need help with.",
	"Hi! What can I do for you today? 😃",
	"Good to see you! Ask me anything you'd like. 🚀",
	"Hello! I'm ready to chat. What's on your mind? 💬",
	"Hi there! Need assistance? I'm here. 🤗",
	"Greetings! Feel free to start a conversation. 💬",
	"Hey! If you have any questions, feel free to ask. ❓",
	"Hello, lovely people! Ready for a chat? 💖",
	"Good day! How may I assist you today? 🌟",
	"Hi, friend! Let me know how I can help. 🌈",
	"Welcome to the chat! What can I do for you? 🚀",
	"Hey! Excited to chat with you. What's up? 😊",
	"Hello, wonderful viewer! How can I assist you? 🌟",
	"Hiya! Ask me anything—I'm here to help. 🤗",
	"Greetings and salutations! What's on your mind? 💭",
	"Hey! 🌞 Ready for a fantastic chat?",
	"Hi! 😄 How can I make your day better?",
	"Welcome! 🎊 Let's have a great conversation!",
	"Hello there! 👀 Anything specific you'd like to discuss?",
	"Greetings, friend! 🌈 How can I assist you today?",
	"Hey! 🚀 Feel free to share your thoughts or questions.",
	"Hiya! 😊 Ready for a chat adventure?",
	"Good day! ☀️ What can I help you with?",
	"Hola! 🌟 How's it going on your end?",
	"Welcome aboard! 🚢 Ready to sail into the conversation?",
	"Hey! 🌺 What brings you to the chat today?",
	"Hello! 😃 Let's make this chat memorable!",
	"Greetings and salutations! 🌈 How can I assist you?",
	"Hi there! 👋 Ready for a chat experience?",
	"Hey you! 🌟 What's on your mind?",
	"Hola amigo! 😊 How can I be of service?",
	"Hi! 👋 Ready for a friendly chat?",
	"Greetings! 🚀 What's the latest in your world?",
	"Hello! 😄 Let's make this chat extraordinary!",
	"Hey there! 🌞 How can I brighten your day?",
	"Hiya! 🌟 Ready for some awesome conversation?",
	"Good day! ☕️ What's brewing in your world?",
	"Welcome! 🎉 How can I add joy to your day?",
	"Hello! 👋 What can I do for you today?",
	"Nice to meet you! 😊 Ready for a chat adventure?",
	"Is there anything specific you'd like assistance with? 🤔",
	"Hey there! 🌟 Feel free to ask me anything.",
	"Greetings! 🌈 I'm here to assist you.",
	"How's your day going? 🌞 I'm here for any questions you may have.",
	"Welcome! 🎉 Let me know what you need help with.",
	"Hi! What can I do for you today? 😃",
	"Good to see you! Ask me anything you'd like. 🚀",
	"Hello! I'm ready to chat. What's on your mind? 💬",
	"Hi there! Need assistance? I'm here. 🤗",
	"Greetings! Feel free to start a conversation. 💬",
	"Hey! If you have any questions, feel free to ask. ❓",
	"Hello, lovely people! Ready for a chat? 💖",
	"Good day! How may I assist you today? 🌟",
	"Hi, friend! Let me know how I can help. 🌈",
	"Welcome to the chat! What can I do for you? 🚀",
	"Hey! Excited to chat with you. What's up? 😊",
	"Hello, wonderful viewer! How can I assist you? 🌟",
	"Hiya! Ask me anything—I'm here to help. 🤗",
	"Greetings and salutations! What's on your mind? 💭",
	"Hey! 🌞 Ready for a fantastic chat?",
	"Hi! 😄 How can I make your day better?",
	"Welcome! 🎊 Let's have a great conversation!",
	"Hello there! 👀 Anything specific you'd like to discuss?",
	"Greetings, friend! 🌈 How can I assist you today?",
	"Hey! 🚀 Feel free to share your thoughts or questions.",
	"Hiya! 😊 Ready for a chat adventure?",
	"Good day! ☀️ What can I help you with?",
	"Hola! 🌟 How's it going on your end?",
	"Welcome aboard! 🚢 Ready to sail into the conversation?",
	"Hey! 🌺 What brings you to the chat today?",
	"Hello! 😃 Let's make this chat memorable!",
	"Greetings and salutations! 🌈 How can I assist you?",
	"Hi there! 👋 Ready for a chat experience?",
	"Hey you! 🌟 What's on your mind?",
	"Hola amigo! 😊 How can I be of service?",
	"Hi! 👋 Ready for a friendly chat?",
	"Greetings! 🚀 What's the latest in your world?",
	"Hello! 😄 Let's make this chat extraordinary!",
	"Hey there! 🌞 How can I brighten your day?",
	"Hiya! 🌟 Ready for some awesome conversation?",
	"Good day! ☕️ What's brewing in your world?",
	"Welcome! 🎉 How can I add joy to your day?",
	"Hello! 👋 What can I do for you today?",
	"Nice to meet you! 😊 Ready for a chat adventure?",
	"Is there anything specific you'd like assistance with? 🤔",
	"Hey there! 🌟 Feel free to ask me anything.",
	"Greetings! 🌈 I'm here to assist you.",
	"How's your day going? 🌞 I'm here for any questions you may have.",
	"Welcome! 🎉 Let me know what you need help with.",
	"Hi! What can I do for you today? 😃",
	"Good to see you! Ask me anything you'd like. 🚀",
	"Hello! I'm ready to chat. What's on your mind? 💬",
	"Hi there! Need assistance? I'm here. 🤗",
	"Greetings! Feel free to start a conversation. 💬",
	"Hey! If you have any questions, feel free to ask. ❓",
	"Hello, lovely people! Ready for a chat? 💖",
	"Good day! How may I assist you today? 🌟",
	"Hi, friend! Let me know how I can help. 🌈",
	"Welcome to the chat! What can I do for you? 🚀",
	"Hey! Excited to chat with you. What's up? 😊",
	"Hello, wonderful viewer! How can I assist you? 🌟",
	"Hiya! Ask me anything—I'm here to help. 🤗",
	"Greetings and salutations! What's on your mind? 💭",
];

export const randomChatGenerator = () => {
	return chatList[Math.floor(Math.random() * chatList.length)];
};
